{% set name = "fishers_exact_test" %}
{% set version = "0.1.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/brentp/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 08602004b4810d43630e2beec97b06ca11b6e2d80cc09205a67eb3fde55ad1c2

build:
  number: 1
  skip: True  # [py2k]
  script:
    - "{{ PYTHON }} setup.py build_ext -j{{ CPU_COUNT }}"
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fisher

about:
  home: http://github.com/brentp/fishers_exact_test
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Simple, fast implementation of Fisher's exact test

extra:
  recipe-maintainers:
    - npavlovikj
    - maxyme
