{% set name = "fisher" %}
{% set version = "0.1.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d378b3f7e488e2a679c6d0e5ea1bce17bc931c2bfe8ec8424ee47a74f251968d

build:
  number: 1
  skip: True  # [py2k and win]
  script:
    - "cythonize src/cfisher.pyx"
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  build:
    - cython
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fisher

about:
  home: http://github.com/brentp/fishers_exact_test
  license: BSD
  license_family: BSD
  # Upsream issue raised, https://github.com/brentp/fishers_exact_test/issues/21
  license_file: ''
  summary: Fast Fisher's Exact Test

extra:
  recipe-maintainers:
    - npavlovikj
