appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UPBS3SxcTuanJrdcKc+h0wkLHula+wTVTi/pLkhkz0JCIdvGxKo+zG+NJcbIvKKPVxjDwXFGYM9G0Z/JXuTWQrPUFzR9Fkkh8H6xfiJ5I8Q99uYWBwxC8B3sK0derQq9HK3o2PZWk1po3Nta//MFBleeQLaDkMvZpphdxGKuHFQ3/Auklz3VFLLwQLPw3wGEQ/TqPOtXi9jrF7c0vDlPSy4Epr3kebUEz1uorfx5ZoRvvhfDhwTANUDws7fwkO72gBlEG/BNJe0vtbzDn5TmjWqkoXRCGBaf3OX6Gxc2HyoHB0NtknV61lnPSV0NBXBi3llS8PYXB8HkjkCi3HFDT8Sns7zgN130vrbzNUqsNOg1d8RFjo8pqKfQQOqpwCLzQGccnJNFDPzv3I6bdA7jjrGBCzxdFxNhENbnlMY49xugXs0tLdRyfw333XjllakXvA+KGYwSzRZdqUVq19+rhU+rLRJu84rU1VMmmHLPurCWV3k7iPVhSAH+bNMSUy236Tw/9dgu3knqi5jeIRicpRcTZiFR/UPwmzohfJUFUOFx7t9DNCBmn252VKjPZSI6HaHoyLQPfTmPta8jHLWOZhU5HVAy99ii/sZ5L3Hcv1biRT3V8UISSOw48d95inwBO1SkCfK72U66p2iafKu04Yg+/i8+khTQTy91TwiB5aQ=}
